export const FILTERED_PROPOSALS_REQUEST = 'FILTERED_PROPOSALS_REQUEST';
export const FILTERED_PROPOSALS_SUCCESS = 'FILTERED_PROPOSALS_SUCCESS';
export const VOTING_PROPOSALS_ACTION = 'VOTING_PROPOSALS_ACTION';
